// filepath: /Users/imran-m/helm-charts-py-fastapi-app/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "python-fastapi-app-helm.fullname" . }}-config
  labels:
    {{- include "python-fastapi-app-helm.labels" . | nindent 4 }}
data:
  db-port: {{ .Values.config.dbPort | quote }}