apiVersion: v1
kind: Secret
metadata:
  name: {{ include "python-fastapi-app-helm.fullname" . }}-secret
  labels:
    {{- include "python-fastapi-app-helm.labels" . | nindent 4 }}
    component: database
type: Opaque
data:
  db-username: {{ .Values.secrets.dbUsername }}
  db-password: {{ .Values.secrets.dbPassword }}
  db-host: {{ .Values.secrets.dbHost }}
  api-key: {{ .Values.secrets.apiKey }}
  jwt-secret: {{ .Values.secrets.jwtSecret }}